### ISSUE TITLE
MVP (0.1) Release Tracking

### ISSUE THREAD

**Issue by goosewobbler** [goosewobbler/dj-helper#4]
Tracking functionality / tasks for completion of the MVP

- [x] Browser Panel displays Bandcamp homepage
- [x] Meta Panel displays tracks from Bandcamp release and track pages
- [x] Meta Panel can preview tracks using bandcamp embeds
- [x] Bandcamp embed can be resized
- [x] Lists play next track when currently playing track ends
- [x] MetaPanel plays next track when currently playing track ends
- [x] Persistent data using electron-store
- [x] Meta Panel / Browser Panel can be resized vertically with a splitter
- [x] List Pane / Browser Pane can be resized horizontally with a splitter
- [x] Window configuration loaded on startup from state
- [x] Embed loaded on startup from state
- [x] Lists can be selected
- [x] Tracks can be added to selected lists
- [x] Tracks can be removed from selected lists
- [x] Tracks can be reordered within a list (buttons)
- [x] Tracks can be reordered within a list (drag & drop)
- [x] Lists play next track when currently playing track ends
- [x] MetaPanel plays next track when currently playing track ends
- [x] Basic CSS for all components
- [x] Create new Browser tab
- [x] Switch Browser tabs
- [x] Close Browser tab
- [x] Tab loading spinner
- [x] Open link in new Browser tab (middle click)
- [x] Browsers configuration loaded on startup from state
- [x] Final CSS tweaks
- [x] Build tooling for publish
- [x] Tested clean install on different OS's
- [x] License

**Comment by goosewobbler** [comment]
Released
